
#ifndef __IEEE802_11_ELEMENT_H__
#define __IEEE802_11_ELEMENT_H__

/* information element ids (ieee std 802.11-2016, 9.4.2.1, table 9-77) */
#define wlan_tag_ssid 0
#define wlan_tag_supp_rates 1
#define wlan_tag_ds_params 3
#define wlan_tag_cf_params 4
#define wlan_tag_tim 5
#define wlan_tag_ibss_params 6
#define wlan_tag_country 7
#define wlan_tag_request 10
#define wlan_tag_bss_load 11
#define wlan_tag_edca_param_set 12
#define wlan_tag_tspec 13
#define wlan_tag_tclas 14
#define wlan_tag_schedule 15
#define wlan_tag_challenge 16
#define wlan_tag_pwr_constraint 32
#define wlan_tag_pwr_capability 33
#define wlan_tag_tpc_request 34
#define wlan_tag_tpc_report 35
#define wlan_tag_supported_channels 36
#define wlan_tag_channel_switch 37
#define wlan_tag_measure_request 38
#define wlan_tag_measure_report 39
#define wlan_tag_quiet 40
#define wlan_tag_ibss_dfs 41
#define wlan_tag_erp_info 42
#define wlan_tag_ts_delay 43
#define wlan_tag_tclas_processing 44
#define wlan_tag_ht_cap 45
#define wlan_tag_qos 46
#define wlan_tag_rsn 48
#define wlan_tag_ext_supp_rates 50
#define wlan_tag_ap_channel_report 51
#define wlan_tag_neighbor_report 52
#define wlan_tag_rcpi 53
#define wlan_tag_mobility_domain 54
#define wlan_tag_fast_bss_transition 55
#define wlan_tag_timeout_interval 56
#define wlan_tag_ric_data 57
#define wlan_tag_dse_registered_location 58
#define wlan_tag_supported_operating_classes 59
#define wlan_tag_ext_chanswitch_ann 60
#define wlan_tag_ht_operation 61
#define wlan_tag_secondary_channel_offset 62
#define wlan_tag_bss_average_access_delay 63
#define wlan_tag_antenna 64
#define wlan_tag_rsni 65
#define wlan_tag_measurement_pilot_transmission 66
#define wlan_tag_bss_available_adm_capa 67
#define wlan_tag_bss_ac_access_delay 68 /* note: also used by wapi */
#define wlan_tag_time_advertisement 69
#define wlan_tag_rrm_enabled_capabilities 70
#define wlan_tag_multiple_bssid 71
#define wlan_tag_20_40_bss_coexistence 72
#define wlan_tag_20_40_bss_intolerant 73
#define wlan_tag_overlapping_bss_scan_params 74
#define wlan_tag_ric_descriptor 75
#define wlan_tag_mmie 76
#define wlan_tag_event_request 78
#define wlan_tag_event_report 79
#define wlan_tag_diagnostic_request 80
#define wlan_tag_diagnostic_report 81
#define wlan_tag_location_parameters 82
#define wlan_tag_nontransmitted_bssid_capa 83
#define wlan_tag_ssid_list 84
#define wlan_tag_multiple_bssid_index 85
#define wlan_tag_fms_descriptor 86
#define wlan_tag_fms_request 87
#define wlan_tag_fms_response 88
#define wlan_tag_qos_traffic_capability 89
#define wlan_tag_bss_max_idle_period 90
#define wlan_tag_tfs_req 91
#define wlan_tag_tfs_resp 92
#define wlan_tag_wnmsleep 93
#define wlan_tag_tim_broadcast_request 94
#define wlan_tag_tim_broadcast_response 95
#define wlan_tag_collocated_interference_report 96
#define wlan_tag_channel_usage 97
#define wlan_tag_time_zone 98
#define wlan_tag_dms_request 99
#define wlan_tag_dms_response 100
#define wlan_tag_link_id 101
#define wlan_tag_wakeup_schedule 102
#define wlan_tag_channel_switch_timing 104
#define wlan_tag_pti_control 105
#define wlan_tag_tpu_buffer_status 106
#define wlan_tag_interworking 107
#define wlan_tag_adv_proto 108
#define wlan_tag_expedited_bandwidth_req 109
#define wlan_tag_qos_map_set 110
#define wlan_tag_roaming_consortium 111
#define wlan_tag_emergency_alert_id 112
#define wlan_tag_mesh_config 113
#define wlan_tag_mesh_id 114
#define wlan_tag_mesh_link_metric_report 115
#define wlan_tag_congestion_notification 116
#define wlan_tag_peer_mgmt 117
#define wlan_tag_mesh_channel_switch_parameters 118
#define wlan_tag_mesh_awake_window 119
#define wlan_tag_beacon_timing 120
#define wlan_tag_mccaop_setup_request 121
#define wlan_tag_mccaop_setup_reply 122
#define wlan_tag_mccaop_advertisement 123
#define wlan_tag_mccaop_teardown 124
#define wlan_tag_gann 125
#define wlan_tag_rann 126
#define wlan_tag_ext_capab 127
#define wlan_tag_preq 130
#define wlan_tag_prep 131
#define wlan_tag_perr 132
#define wlan_tag_pxu 137
#define wlan_tag_pxuc 138
#define wlan_tag_ampe 139
#define wlan_tag_mic 140
#define wlan_tag_destination_uri 141
#define wlan_tag_u_apsd_coex 142
#define wlan_tag_dmg_wakeup_schedule 143
#define wlan_tag_extended_schedule 144
#define wlan_tag_sta_availability 145
#define wlan_tag_dmg_tspec 146
#define wlan_tag_next_dmg_ati 147
#define wlan_tag_dmg_capabilities 148
#define wlan_tag_dmg_operation 151
#define wlan_tag_dmg_bss_parameter_change 152
#define wlan_tag_dmg_beam_refinement 153
#define wlan_tag_channel_measurement_feedback 154
#define wlan_tag_cckm 156
#define wlan_tag_awake_window 157
#define wlan_tag_multi_band 158
#define wlan_tag_addba_extension 159
#define wlan_tag_nextpcp_list 160
#define wlan_tag_pcp_handover 161
#define wlan_tag_dmg_link_margin 162
#define wlan_tag_switching_stream 163
#define wlan_tag_session_transition 164
#define wlan_tag_dynamic_tone_pairing_report 165
#define wlan_tag_cluster_report 166
#define wlan_tag_replay_capabilities 167
#define wlan_tag_relay_transfer_param_set 168
#define wlan_tag_beamlink_maintenance 169
#define wlan_tag_multiple_mac_sublayers 170
#define wlan_tag_u_pid 171
#define wlan_tag_dmg_link_adaptation_ack 172
#define wlan_tag_mccaop_advertisement_overview 174
#define wlan_tag_quiet_period_request 175
#define wlan_tag_quiet_period_response 177
#define wlan_tag_qmf_policy 181
#define wlan_tag_ecapc_policy 182
#define wlan_tag_cluster_time_offset 183
#define wlan_tag_intra_access_category_priority 184
#define wlan_tag_scs_descriptor 185
#define wlan_tag_qload_report 186
#define wlan_tag_hcca_txop_update_count 187
#define wlan_tag_higher_layer_stream_id 188
#define wlan_tag_gcr_group_address 189
#define wlan_tag_antenna_sector_id_pattern 190
#define wlan_tag_vht_cap 191
#define wlan_tag_vht_operation 192
#define wlan_tag_vht_extended_bss_load 193
#define wlan_tag_vht_wide_bw_chswitch 194
#define wlan_tag_transmit_power_envelope 195
#define wlan_tag_vht_channel_switch_wrapper 196
#define wlan_tag_vht_aid 197
#define wlan_tag_vht_quiet_channel 198
#define wlan_tag_vht_operating_mode_notification 199
#define wlan_tag_upsim 200
#define wlan_tag_reduced_neighbor_report 201
#define wlan_tag_tvht_operation 202
#define wlan_tag_device_location 204
#define wlan_tag_white_space_map 205
#define wlan_tag_ftm_parameters 206
#define wlan_tag_s1g_bcn_compat 213
#define wlan_tag_twt 216
#define wlan_tag_s1g_capabilities 217
#define wlan_tag_vendor_specific 221
#define wlan_tag_s1g_operation 232
#define wlan_tag_cag_number 237
#define wlan_tag_ap_csn 239
#define wlan_tag_fils_indication 240
#define wlan_tag_dils 241
#define wlan_tag_fragment 242
#define wlan_tag_rsnx 244
#define wlan_tag_extension 255

/* element id extension (eid 255) values */
#define wlan_tag_ext_assoc_delay_info 1
#define wlan_tag_ext_fils_req_params 2
#define wlan_tag_ext_fils_key_confirm 3
#define wlan_tag_ext_fils_session 4
#define wlan_tag_ext_fils_hlp_container 5
#define wlan_tag_ext_fils_ip_addr_assign 6
#define wlan_tag_ext_key_delivery 7
#define wlan_tag_ext_wrapped_data 8
#define wlan_tag_ext_ftm_sync_info 9
#define wlan_tag_ext_extended_request 10
#define wlan_tag_ext_estimated_service_params 11
#define wlan_tag_ext_fils_public_key 12
#define wlan_tag_ext_fils_nonce 13
#define wlan_tag_ext_future_channel_guidance 14
#define wlan_tag_ext_owe_dh_param 32
#define wlan_tag_ext_password_identifier 33
#define wlan_tag_ext_he_capabilities 35
#define wlan_tag_ext_he_operation 36
#define wlan_tag_ext_he_mu_edca_params 38
#define wlan_tag_ext_spatial_reuse 39
#define wlan_tag_ext_ocv_oci 54
#define wlan_tag_ext_short_ssid_list 58
#define wlan_tag_ext_he_6ghz_band_cap 59
#define wlan_tag_ext_edmg_capabilities 61
#define wlan_tag_ext_edmg_operation 62
#define wlan_tag_ext_mscs_descriptor 88
#define wlan_tag_ext_tclas_mask 89
#define wlan_tag_ext_rejected_groups 92
#define wlan_tag_ext_anti_clogging_token 93
#define wlan_tag_ext_pasn_params 100

#endif
